name: "Setup Environment"
description: "Installs Python and dependencies"
inputs:
  requirements_file:
    description: "Path to requirements.txt file"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements_file }}
